routes/comment.py
from routes import *
from models.weibo import Comment
from models.user import User


main = Blueprint('comment', __name__)


@main.route('/comment/add', methods=['POST'])
def add():
    u = current_user()
    form = request.form
    c = Comment(form)
    c.username = u.username
    if c.valid():
        c.save()
    else:
        abort(400)
    # 蓝图中的 url_for 需要加上蓝图的名字，这里是 todo
    return redirect(url_for('weibo.public_index'))

routes/weibo.py
# 调用__init__模块
from routes import *
# 调用Weibo 数据模型和Comment 数据模型
from models.weibo import Weibo
from models.weibo import Comment


# 用蓝图把weibo 变成一个模块
main = Blueprint('weibo', __name__)


# 把square_index 视图函数注册为weibo 模块的路由'/weibo'
@main.route('/')
def public_index():
    u = current_user()
    if u is None:
        return redirect(url_for('user.index'))
    weibo_list = Weibo.query.order_by(Weibo.id.desc()).all()
    for w in weibo_list:
        w.comment = w.comments()
        w.commentNum = len(w.comment)
        w.avatar = w.get_avatar()
        for c in w.comment:
            c.avatar = c.get_avatar()
    return render_template('weibo_public.html', weibos=weibo_list)


# # 把personal_index 视图函数注册为weibo 模块的路由'/weibo/personal'
# @main.route('/personal')
# def personal_index():
#     u = current_user()
#     weibo_list = u.get_weibos
#     return render_template('weibo_personal.html', weibos=weibo_list)


# 把add 函数注册为weibo 模块的路由'/weibo/add'
@main.route('/add', methods=['POST'])
def add():
    u = current_user()
    form = request.form
    w = Weibo(form)
    w.username = u.username
    if w.valid():
        w.save()
    else:
        abort(400)
    return redirect(url_for('weibo.public_index'))


@main.route('/delete/<int:weibo_id>')
def delete(weibo_id):
    u = current_user()
    w = Weibo.query.get(weibo_id)
    user = User.query.filter_by(username=w.username).first()
    if u is user:
        w.delete()
    return redirect(url_for('weibo.public_index'))

templates/user_login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>信鸽-用户登录</title>
  <link rel="shortcut icon" href="../static/img/favicon.ico">
  <link href="../static/css/flat-ui.css" rel="stylesheet">
  <link href="../static/css/user_login.css" rel="stylesheet">
</head>
<body>
  <div class="center">
    <h3>信鸽</h3>
    <div class="img">
      <img src="../static/img/png/Chat.png">
      <p>欢迎你，朋友</p>
    </div>
    <div class="form">
      <form action="/user/login" method="post">
      <input type="text" class="form-control login-field" name="username"
             placeholder="请输入用户名" id="loginName">
      <label class="login-field-icon fui-user" for="loginName"></label>
      <br>
      <input type="password" class="form-control login-field" name="password"
             placeholder="请输入密码" id="loginPass">
      <label class="login-field-icon fui-lock" for="loginPass"></label>
      <br>
      <button type="submit" class="btn btn-primary btn-lg">登录</button>
      <a href="/user/switch" class="login-link">未有账号？请注册</a>
    </form>
    </div>
  </div>
</body>
</html>

templates/user_register.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>信鸽-用户注册</title>
  <link rel="shortcut icon" href="../static/img/favicon.ico">
  <link href="../static/css/flat-ui.css" rel="stylesheet">
  <link href="../static/css/user_login.css" rel="stylesheet">
</head>
<body>
  <div class="center">
    <h3>信鸽</h3>
    <div class="img">
      <img src="../static/img/png/chat.png">
      <p>欢迎你，朋友</p>
    </div>
    <div class="form">
      <form action="/user/register" method="post">
        <input type="text" class="form-control login-field" name="username"
               placeholder="请输入用户名(至少2位)" id="registerName">
        <label class="login-field-icon fui-user" for="registerName"></label>
        <br>
        <input type="password" class="form-control login-field" name="password"
               placeholder="请输入密码(至少6位)" id="registerPass">
        <label class="login-field-icon fui-lock" for="registerPass"></label>
        <br>
        <span class="spanGender">性别:</span>
        <label class="gender"><input name="gender" type="radio" value="male">少侠</label>
        <label class="gender"><input name="gender" type="radio" value="female">女侠</label>
        <button type="submit" class="btn btn-primary btn-lg">注册</button>
        <a href="/" class="login-link">已有账号？请登录</a>
      </form>
    </div>
  </div>
</body>
</html>

templates/weibo_public.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>信鸽-广场</title>
  <link rel="shortcut icon" href="../static/img/favicon.ico">
  <link href="../static/css/flat-ui.css" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
  <link href="../static/css/weibo_public.css" rel="stylesheet">
  <!--<script src="../static/js/weibo.js"></script>-->
</head>
<body>

  <div id="nav">
    <div class="navBox clearfix">
      <h4>信鸽</h4>
      <ul class="clearfix">
        <li><a href={{ url_for("weibo.public_index") }}>百晓生</a></li>
        <li><a href="/user/logout">登出</a></li>
      </ul>
    </div>
  </div>

  <div id="weibo" class="center clearfix">

    <div class="content">
      <div class="weiboInput">
        <h5>有什么江湖秘闻想告诉百晓生？</h5>
        <form action={{ url_for("weibo.add") }} method="post">
          <textarea id="id-weibo-input" class="form-control" name="content"></textarea>
          <br>
          <input id="id-weibo-button" type="submit" class="btn btn-primary" value="飞鸽传书">
        </form>
      </div>

      {% for w in weibos %}
      <div id="weibo-container" class="container">
        <div class="weiboCell clearfix" data-id="{{ w.id }}">
          <img src="{{ w.avatar }}">
          <div class="imgRight">
          <div class="contentBox">
            <h6>{{ w.username }}</h6>
            <p class="weiboContent">{{ w.content }}</p>
            <div class="bottom clearfix">
            <p class="time">发布于：<span>{{ w.created_time }}</span></p>
            <a class="weibo-delete" href={{ url_for("weibo.delete", weibo_id=w.id) }}><span class="delete-weibo fui-cross" data-id="{{ w.id }}">删除</span></a>
            <span class="showComment fui-bubble" data-id="{{ w.id }}">评论({{ w.commentNum }})</span>
            </div>
          </div>
          <div id="comment-{{ w.id }}" class="commentCell">
            <form action={{ url_for("comment.add") }} method="post">
              <input type="hidden" name="weibo_id" value="{{ w.id }}">
              <input class="commentInput form-control" name="content">
              <input class="commentSubmit btn btn-primary" type="submit" value="评论">
            </form>
            {% for c in w.comment %}
            <div class="commentContent clearfix">
              <img src="{{ c.avatar }}">
              <div class="commentBottom clearfix">
                <p class="comment-content"><span>{{ c.username }}</span>：{{ c.content }}</p>
                <p class="comment-time">{{ c.created_time }}</p>
              </div>
            </div>
            {% endfor %}
          </div>
          </div>
        </div>
      </div>
      {% endfor %}

    </div>

    <div class="sidebar">
        <img src="../static/img/舞剑.jpg">
        <br>
        <!--<audio src="../static/music.mp3" controls="controls"></audio>-->
        <p>
          游侠某 名远传 而今江湖谈<br>
          仇者多 友两三 但逢敌手难<br>
          雨尽碎 风如潮 出手引狂澜<br>
          未收招 三声笑 皆醉了<br>
          远风急 忽回首 明月漫千山<br>
          天地渺 意气满 踏歌至长安<br>
          灯影繁 酒正暖 满座均贪欢<br>
          众人酣 拂衣散 乌云然<br>
          唯此间江湖年少 偏爱纵横天下<br>
          恩仇趁年华轻剑快马<br>
          红尘未破也无甚牵挂 只恋生杀<br>
          醉里论道 醒时折花<br>
          游侠某 名远传 而今江湖谈<br>
          仇者多 友两三 相逢皆恨晚<br>
          檐上霜 窗边月 为我留一盏<br>
          过江南 踏天山 不曾还<br>
          剑影翩 血光寒 似鬼亦似仙<br>
          说书人 应笑我 既疯也如癫<br>
          辩正邪 如明月 今圆别时缺<br>
          倒不如 一拍案 入寒渊<br>
          唯此间江湖年少 偏爱纵横天下<br>
          恩仇趁年华轻剑快马<br>
          红尘未破也无甚牵挂 只恋生杀<br>
          醉里论道 醒时折花<br>
          唯此间江湖年少 偏爱纵横天下<br>
          恩仇趁年华轻剑快马<br>
          红尘未破也无甚牵挂 只恋生杀<br>
          醉里论道 醒时折花<br>
          传言道江湖年少 不谙世事繁华<br>
          是敌是友不妨一战罢<br>
          待何人何年有心与我 拭血论茶<br>
          梦里依旧 明月天涯
        </p>
    </div>
  </div>

  <div id="footer">
    Copyright © 2016 信鸽.     当前版本 beta 1.0.     昜聿
  </div>


  <script>
    $(document).ready(function() {
        $('.showComment').on('click', function(){
            var weiboId = $(this).data('id')
            var selector = '#comment-' + weiboId
            $(selector).slideToggle()
         });
    })
    </script>
</body>
</html>